basePath: /
definitions:
  company_agent_service.Company_data_info:
    properties:
      cost:
        type: number
      id:
        type: integer
      name:
        type: string
    type: object
  company_agent_service.Get_company_data_args:
    properties:
      ids:
        items:
          type: integer
        type: array
    type: object
  company_agent_service.Get_company_data_reply:
    properties:
      err:
        $ref: '#/definitions/errcode.Errcode'
      list:
        items:
          $ref: '#/definitions/company_agent_service.Company_data_info'
        type: array
    type: object
  errcode.Errcode:
    properties:
      code:
        description: 错误码
        type: integer
      from:
        description: '来源 {3000: user_service}'
        type: integer
      msg:
        description: 错误消息
        example: 错误消息
        type: string
    type: object
info:
  contact:
    email: danyang.chen@snkad.cn
    name: Snk技术开发中心
  description: 公司代理服务
  termsOfService: https://github.com/DAN-AND-DNA?tab=stars
  title: company-agent-service
  version: 0.1.0
paths:
  /v1.company-agent-service.Get_company_data:
    post:
      consumes:
      - application/json
      description: 查询公司数据
      parameters:
      - description: args
        in: body
        name: args
        required: true
        schema:
          $ref: '#/definitions/company_agent_service.Get_company_data_args'
      produces:
      - application/json
      responses:
        "200":
          description: reply
          schema:
            $ref: '#/definitions/company_agent_service.Get_company_data_reply'
      summary: 查询公司数据
      tags:
      - company-agent-service
swagger: "2.0"
